# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Blackwall' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Blackwall
  pod 'Bugsnag'


  target 'BlackwallTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
